apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  imagePullSecrets:
    - name: nvcr.dgxkey
  containers:
    - name: pytorch-container
      image: nvcr.io/nvidia/pytorch:18.05-py3
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      extendedResourceRequests: ["nvidia-gpu"]
      volumeMounts:
        - name: nfs-vol 
          mountPath: /nfs
  volumes:
    - name: nfs-vol
      persistentVolumeClaim:
        claimName: nfs-pvc 
  extendedResources:
    - name: "nvidia-gpu"
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          nvidia.com/gpu: 1

